### ISSUE TITLE
或许我们之间有一些误会

### ISSUE THREAD

**Issue by WForst-Breeze** [WForst-Breeze/sth#1]
@KGOne-666 很抱歉打扰您，因为我无法获取到您的联系方式，我只能通过这种方式与您沟通，请您谅解。
您或许也知道了，一个月前发生了一些不愉快的事情，导致社区的氛围一直很僵硬，所以在那次事件之后，包括我在内的部分 Collaborator 都在尽可能避免类似的事情发生，至少从我个人而言，我会去及时制止那些态度不太好的 Collaborator（如果我看见了并且还来得及的话），今天这种事情发生，无疑是使我十分悲伤的。

但是我们之间或许有一些误会。

首先我向您道歉，可能是我的表意不明导致了您的误解，这点在我，真的很抱歉，因为我今天看见您一直在回复 discussions，这一点我很支持并且非常乐意和您一起讨论有关问题，但是呢……请允许我举一个例子，如果您介意，我立马删除

![image](https://user-images.githubusercontent.com/110760354/214577810-034e3ea6-5778-466e-aa89-de38b731c228.png)

您可以看见，导出整合包功能投票排名非常靠前，很多玩家都想要这个功能，您所提及的观点可能会使得某些不理智的玩家上来就开喷，再次导致一个月前的事件。所以我提醒了您一下，我其实可以直接 Hide 而不提醒，现在看或许这个是个更好的选择，真的抱歉…… 当时我只想着不要出现一个月前的情况，而没有考虑周到，真的很抱歉

我在给您发的回复中，向您表示了感谢，如果这次您能原谅我，那么我将更加感谢

之所以我不直接在PCL2仓库下回复您，同样是那个原因，并非我自己脸面挂不住，但是如果您不接受我的道歉，并希望我在 PCL2 仓库公开道歉，那么我将照做，决定权在您，毕竟我是那个疏忽大意的人。

请允许我做最后的自我“辩解”，我在仓库中向来是比较……和蔼的个人认为，但是请不要因为我一个人就对整个 Collaborator 产生误解，这都是我的个人行为，我也没有想到我会让您这么失落、伤心，我很自责。

祝好。

**Comment by WForst-Breeze** [comment]
那条提醒我也是咬文嚼字，尽可能不说得过于尖锐从而激怒您，但没想到……唉

**Comment by KGOne-666** [comment]
我看出来你在咬文嚼字 , 我一直在想你们为什么这样子,  我说的是那个什么什么HIm的 不是说你

**Comment by KGOne-666** [comment]
我真的是发自内心在帮忙, 只是在错误的时间

**Comment by KGOne-666** [comment]
github回复功能有点迷

**Comment by KGOne-666** [comment]
反正我不是说你,我看出来了你回复怎么奇奇怪怪的,不用道歉了 ,我都没在说你

**Comment by KGOne-666** [comment]
只是我认真的回答却被说：'你看清出问题了吗，看清再回答。' 感到难受罢了
我说的是另外一个collaborator

**Comment by KGOne-666** [comment]
# 那你把我之前的评论全部删了 
# 还有其他collaborate回复我也删了 
反正相关信息全部删掉就行了 
 我对你没有指责的意思 你做的是对的 
我只是不知道你们为什么会这样子 
后来我看了那个什么公告才知道的

**Comment by KGOne-666** [comment]
看那个名称叫discussion
应该是随便讨论的 
要不你们开一个discord？（国外游戏交流平台）还可以集成GitHub 进行联动

**Comment by WForst-Breeze** [comment]
> # 那你把我之前的评论全部删了
> # 还有其他collaborate回复我也删了
> 反正相关信息全部删掉就行了 我对你没有指责的意思 你做的是对的 我只是不知道你们为什么会这样子 后来我看了那个什么公告才知道的

虽然但是，我对此毫不知情……Collaborator是无法删除评论的TwT

**Comment by KGOne-666** [comment]
你们之前在哪里聊天啊 
在哪吵架
用的是QQ群 ？

**Comment by WForst-Breeze** [comment]
> 我真的是发自内心在帮忙, 只是在错误的时间

真的很感谢！不过我也会和相关 Collaborator 沟通的

**Comment by KGOne-666** [comment]
对我进行回复的collaborate可以删除他自己发的信息

**Comment by WForst-Breeze** [comment]
吵架大部分都在第三方的群聊和PCL2仓库直接吵

**Comment by KGOne-666** [comment]
另外 你们处理事务都是用邮件吗 ？
discord很方便 我用过了

**Comment by KGOne-666** [comment]
我在各大平台发表评论 帮助他人
在这里的回复让我感觉有点奇怪 
后来我凭借直觉找到了原因

**Comment by WForst-Breeze** [comment]
是的，在 PCL2 仓库有动态的时候我们会收到邮件，Discord 的话，龙猫不打算弄，那就没办法喽，不过有什么事情可以随时加我QQ：3482098038（虽然不怎么在线

**Comment by KGOne-666** [comment]
我不加人的

**Comment by KGOne-666** [comment]
想做雷锋 
做好事不留名

**Comment by KGOne-666** [comment]
那我对一些建议有观点的话 
能不能评论呢
在哪里可以畅所欲言

**Comment by WForst-Breeze** [comment]
> 我在各大平台发表评论 帮助他人 在这里的回复让我感觉有点奇怪 后来我凭借直觉找到了原因

对……现在大家都很敏感，也再次感谢您，有些 Collaborator 说话有些尖锐，但他们本意都是好的，毕竟都是义务来的。

**Comment by KGOne-666** [comment]
关键你们互相都不知道什么情况 就很容易造成一些不好的东西

**Comment by KGOne-666** [comment]
上个月骂人的那个人几岁啊

**Comment by WForst-Breeze** [comment]
看样子年纪不大，属于那种懂一点但不多的样子，大概12岁左右我猜

**Comment by KGOne-666** [comment]
我建议吧 你想更新就更新 不想更新就不更新 
建议看看就好 
 要是我做软件的话 既然都是不盈利的 
那就把基本功能做好就行了 
要是有人吵就拉黑算了 
只要别错怪我这种真心帮助别人的人

**Comment by KGOne-666** [comment]
我是从这个出发点来建议的
不要老是让开发者改进软件
自己找其他方法解决

**Comment by KGOne-666** [comment]
有时候骂人才能好好说话 
像他这种无理取闹就不理他

**Comment by KGOne-666** [comment]
我是MC老玩家  最近一直玩研究模组整合包 
发现问题 解决问题 
然后看别人提出问题
 有思路了就回答一下

**Comment by WForst-Breeze** [comment]
是的，现在的网络真的……哈哈……
btw，你或许可以经常去提问板块看看，这里经常有需要帮助的人，或爱发电的PCL小论坛也可以

**Comment by KGOne-666** [comment]
你们没必要做的跟移动客服一样 
每条都回复吧 
非盈利软件基本功能做好 我觉得就OK了

**Comment by KGOne-666** [comment]
我遇见了好多开发者
issue一大堆
里面的评论寥寥无几 
 基本没有吵架的情况

**Comment by WForst-Breeze** [comment]
上个月那个人就是因为龙猫生病issue一大堆没人回才造成了那次事件的，但是从我们的角度看，我们是志愿者，但我们坚持的原因就是……热爱？

**Comment by KGOne-666** [comment]
我遇到正常的流程 就是提交bug 然后就没有然后了

**Comment by KGOne-666** [comment]
你们这个项目的开发者经常玩MC啊

**Comment by KGOne-666** [comment]
你这个启动器
只需要提供下载功能 
我觉得就已经很好了 
我用了一堆启动器 
这个对我来说是最好的

**Comment by WForst-Breeze** [comment]
常玩，就我个人而言，从大概二三年级开始玩……？不记得了具体，到现在也有七八年左右了，到初中补票买了正版，现在三个正版账号（

**Comment by KGOne-666** [comment]
我现在还是在玩学习版
以后再入正

**Comment by KGOne-666** [comment]
启动器要做的就是启动游戏 
 从这个出发点就行了 
没必要搞那么多 
要学会断舍离啊 
要不然天天那么多东西 谁搞啊 
要是我是这个项目的开发者 
我自己发现什么问题 然后自己解决 
软件只是为了更方便

**Comment by WForst-Breeze** [comment]
您说的没错，但现在启动器家族太卷了，为了更多人使用这个作品，不得不一直自我完善

**Comment by KGOne-666** [comment]
你们没必要回复评论那么勤奋 
花大量时间琢磨软件 
让自己玩游戏更方便

**Comment by KGOne-666** [comment]
在我看来 这个启动器已经接近完美了

**Comment by KGOne-666** [comment]
像微软win 11被一堆人骂 
 我自己用着感觉不错啊 
右键菜单不喜欢 
那就换win 10的右键菜单 
百度一下就行了

**Comment by KGOne-666** [comment]
还有你跟我说话 不要说您 感觉非常的奇怪

**Comment by KGOne-666** [comment]
像我这种玩家一般 
每一种都会用

**Comment by KGOne-666** [comment]
玩我的世界
最好懂英文 
去外国网站

**Comment by KGOne-666** [comment]
虽然我大部分都是右键点翻译的

**Comment by KGOne-666** [comment]
外国的模组都是免费的 
我的世界的初衷是什么 
开放  很多种可能性 
 我玩了各种游戏
 后来我只玩我的世界 
只有我的世界是最好玩的

**Comment by KGOne-666** [comment]
好了 
你现在可以把这个全部删掉 
我们有缘再见

**Comment by KGOne-666** [comment]
把这个issue删除

**Comment by WForst-Breeze** [comment]
抱歉刚刚有点事没来得及回复……好的，那么我们有缘再见，希望再次看到你
